### ISSUE TITLE
[BUG] Solar Panel

### ISSUE THREAD

**Issue by cgkz2107** [Faran23/SolarPanels#1]
Whenever we enter for example the nether and then come back the upgraded solar panels just isn't upgraded anymore it just goes back to normal.

**To Reproduce**
1. Upgrade your Solar Panel
2. Go to any other realm
3. Return to the Overworld
4. Check your Solar Panel
5. Sees that its not upgraded with whatever you upgraded it with whether it was a nether star or diamond

**Expected behavior**
Expected it to stay upgraded instead of going back everytime I go to another realm

**Desktop (please complete the following information):**
 - 1.20.1
Fix as soon as possible, its a very convenient mod

**Comment by Faran23** [comment]
Should be fixed with v0.1.1 coming shortly, I will leave the issue open for a few more days in case it is still not resolved.
